name = "markvale"
version = "1.0.0"
vale_version = "0.1.1"
author = "Evan Ovadia"
git = "https://github.com/Verdagon/markvale"
readme = "README.md"

[[dependencies]]
name = "stdlib"
version = "0.1.0"
allow_native = true
